version: '3'
services:
  nginx:
    image: nginx:latest
    ports:
      - "8090:80"
    volumes:
      - ./nginx-config:/etc/nginx/conf.d
      - /var/cfg2html/:/usr/share/nginx/html/
    networks:
      - cfg2html-network

networks:
  cfg2html-network:
    driver: bridge
